sudo: false
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
env:
  - TEST_SYMLINK="no"
  - TEST_SYMLINK="yes"
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - bundle exec rake before_script
after_script:
  - bundle exec rake after_script
